python:
  build: ./python
  ports:
    - 8888:8888
  volumes:
    - ../datasets/:/home/root/datasets
    - ${XAUTHORITY}:/tmp/.docker.xauth:rw
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/tmp/.docker.xauth:rw
    - HOST_HOSTNAME=${HOSTNAME}
  tty: true
  net: host
  working_dir: /home/root/datasets
  privileged: true
  